# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
#
# Also check out the dprint check action, which gives a simple pass/fail result:
# https://github.com/marketplace/actions/dprint-check-action
---
name: Install dprint
description: A GitHub Action to install the dprint code formatter.
author: kjanat
branding: { icon: terminal, color: blue }

inputs:
  version:
    description: The dprint version to install (e.g., "0.51.1"; defaults to "latest").
    required: false
    default: latest

outputs:
  version: { description: Installed dprint version, value: "${{ steps.dprint.outputs.version }}" }
  location: { description: Path to the installed dprint binary, value: "${{ steps.dprint.outputs.location }}" }

runs:
  using: composite
  steps:
    - name: Install dprint
      id: dprint
      shell: bash
      working-directory: ${{ github.action_path }}
      env: { DPRINT_VERSION: "${{ inputs.version }}" }
      run: ./install.sh
