# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
#
# Also check out the dprint check action, which gives a simple pass/fail result:
# https://github.com/marketplace/actions/dprint-check-action
---
name: Install dprint
description: A GitHub Action to install the dprint code formatter with caching.
author: kjanat
branding: { icon: terminal, color: blue }

inputs:
  version:
    description: The dprint version to install (e.g., "0.51.1"; defaults to "latest").
    required: false
    default: latest

outputs:
  version: { description: Installed dprint version }
  location: { description: Path to the installed dprint binary }

runs:
  using: node24
  main: dist/index.js
  post: dist/post/index.js
  post-if: success()
